
apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: my-pipeline
build:
  artifacts:
  - image: 'gcr.io/mlops-dev-env/caip-tfx-bqml'
    context: .
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:demo"
